### ISSUE TITLE
slight overlap between logo and title when using navigation to jump to a section

### ISSUE THREAD

**Issue by tansaku** [NeuroGrid/folk-on-the-hill#1]
<img width="390" alt="screen shot 2019-02-02 at 17 21 55" src="https://user-images.githubusercontent.com/30216/52167183-23cad980-270f-11e9-8094-158a367d1518.png">

This was in chrome 71 on osx 10.10.5

**Comment by javpet** [comment]
This has been fixed Sam, please re-test: https://javpet.github.io/folk-on-the-hill/

**Comment by tansaku** [comment]
big improvement @javpet - still a slight overlap - but if the client is happy I'll be happy with this :-)

**Comment by javpet** [comment]
I see it, I'll refactor today the <section> elements and then the issue will be solved.
