### ISSUE TITLE
slight leakage of text from one section to another when viewed on older ios mobile (10.2.1)

### ISSUE THREAD

**Issue by tansaku** [NeuroGrid/folk-on-the-hill#2]
![img_0061](https://user-images.githubusercontent.com/30216/52167210-8ae88e00-270f-11e9-8226-ba971b3a1344.PNG)

**Comment by javpet** [comment]
Fixed this one, thanks Sam! Please check again: https://javpet.github.io/folk-on-the-hill/

**Comment by tansaku** [comment]
looks great - wonderful work @javpet !
