### ISSUE TITLE
Google structured data for SEO

### ISSUE THREAD

**Issue by javpet** [NeuroGrid/folk-on-the-hill#35]

**Comment by javpet** [comment]
Fixing https://github.com/NeuroGrid/folk-on-the-hill/pull/37

**Comment by tansaku** [comment]
thanks @javpet not sure that we need the "Fixing #37" in the issue as when you put "fixes #35" in the PR it auto links here - of course if you like the cross-linkage that's good, but just thinking of trying to save you the extra effort :-)
