### ISSUE TITLE
client would like this map included

### ISSUE THREAD

**Issue by tansaku** [NeuroGrid/folk-on-the-hill#4]
http://content.tfl.gov.uk/bus-route-maps/harrow-on-the-hill-071016.pdf

below the information on the buses

**Comment by javpet** [comment]
Do you mean adding a link to the map @tansaku or more like putting this whole map there? I would suggest more the first, so that would be less heavy for the site, and also not breaking the outlook of the site.

**Comment by tansaku** [comment]
the client wasn't clear - a link sounds good to start with

**Comment by javpet** [comment]
Fixes https://github.com/NeuroGrid/folk-on-the-hill/pull/12
