### ISSUE TITLE
need to support italics bold and underline in the biographies

### ISSUE THREAD

**Issue by tansaku** [NeuroGrid/folk-on-the-hill#46]
netlify if passing them through, but there is no associated style change

**Comment by javpet** [comment]
which parts should be bold and underline in the text?

**Comment by tansaku** [comment]
@javpet we want to specify with em and strong tags in the biography text - see here:

![](https://dl.dropbox.com/s/ypmwa4mxjmf8l0q/Screenshot%202019-03-05%2020.52.22.png?dl=0)

em tags passed through but style not changed - maybe need to specify explicitly for that font?

**Comment by javpet** [comment]
The bold text is possible to specify by font-weight: 700, but the chosen English Grotesque font is not supporting 'italic' so the browser will imitate the 'italic' look & feel

Maybe with inline styling?

**Comment by tansaku** [comment]
@javpet what would inline styling involve?

**Comment by javpet** [comment]
```
<span style="font-weight: 700">{content here}</span>
<span style="font-style: italic">{content here}</span>
```

**Comment by tansaku** [comment]
cool - and maybe we could even add that to css for the section like:

```css
i, em {
  font-style: italic;
}
```

?

**Comment by javpet** [comment]
Yeah that might be working too
