### ISSUE TITLE
might be nice to have, place to submit email address to be notified when tickets go on sale

### ISSUE THREAD

**Issue by tansaku** [NeuroGrid/folk-on-the-hill#6]
but likely we'll have the ticket links up soon enough that it's maybe not worth it

**Comment by javpet** [comment]
Sure, I would recommend around the tickets area! Where should the emails be delivered after sign up? Maybe a Mailchimp or other service?

**Comment by tansaku** [comment]
yes, or mailjet - apparently they are the only GDPR compliant mailer

**Comment by tansaku** [comment]
kind of redundant now tickets are already on sale ...
